deployment/urls.py
from django.urls import path
from . import views
from deployment.dashboards import deployment

app_name = 'deployment'
urlpatterns = [
    path('index', views.IndexView.as_view(),
         name='deployment_index'),
    path('dashboard', views.DashboardView.as_view(),
         name='deployment_dashboard'),
    path('form_test', views.form_handler,
         name='form_test'),
]

forecasting/urls.py
from django.urls import path
from forecasting.dashboards import forecast_accuracy
from forecasting.dashboards import forecast_accuracy_madec
from forecasting.dashboards import forecast_accuracy_v1
from forecasting.dashboards import forchest
from . import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

app_name = 'forecasting'
urlpatterns = [
    path('index', views.IndexView.as_view(),
         name='index'),
#     path('input_interface', views.InputInterfaceView.as_view(),
#          name='input_interface'),
    path('accuracy', views.ForecastAccuracyView.as_view(),
         name='forecast_accuracy'),
    path('accuracy_madec', views.ForecastAccuracyMadecView.as_view(),
         name='forecast_accuracy_madec'),
    path('accuracy_test', views.ForecastAccuracyV1View.as_view(),
         name='forecast_accuracy_v1'),
#     url(r'^input_interface/new/$', views.CreateProductView.as_view(), name='input_interface_new'),
    path('input_interface/<int:pk>', views.UpdateForcastView.as_view(),
         name='input_interface_update'),
    path('version/listold', views.VersionList.as_view(),
         name='version_list_old'),
    path('version/', views.FilteredVersionListView.as_view(),
         name='version_list'),
    path('version/<int:pk>', views.VersionDetailView.as_view(),
         name='version_detail'),
    path('version/update/<int:pk>', views.VersionUpdateView.as_view(),
         name='version_update'),
    path('forecast/v<int:version_id>', views.ForecastListByVersionView.as_view(),
         name='forecast_list'),
#     path('forecast/v<int:version>/getpivottable', views.getPivotData),
    path('forecast/v<int:version_id>/update-quantity', views.updateQuantity, name = 'ajax_update_forecast_qty'),
    path('forecast/v<int:version_id>/add-quantity', views.addQuantity, name = 'ajax_add_forecast_qty'),
    path('forecast/v<int:version_id>/add-forecast', views.addForecast, name = 'ajax_add_forecast'),
    path('forecast/v<int:version_id>/send-review-request',
         views.sendReviewRequest, name='send_review_request'),
    path('forecast/v<int:version_id>/approve-review-request',
         views.approveReviewRequest, name='approve_review_request'),
#     path('forchest', views.ForchestView.as_view(), name='forchest'),
    path('forchest/<int:versiondetail_id>',
         views.ForchestView.as_view(), name='forchest'),
    path('version-detail', views.VersionDetailView.as_view(), name='version_detail'),

#     url(r'^input_interface/(?P<pk>\d+)/$',
#         views.UpdateProductView.as_view(), name='input_interface_update'),
#     #export
#     url(r'export/$', login_required(views.ForecastExport.as_view()), name='forecast_export'),
#     #import
#     url(r'import/$', login_required(views.ForecastImport.as_view()), name='forecast_import'),

#     url(r'process_import/$',
#         login_required(views.ForecastProcessImport.as_view()), name='process_import'),
    path('simple_upload', views.simple_upload,
         name='simple_upload'),


]

inventory/urls.py
from django.urls import path
from inventory.dashs import stock_image
from inventory.dashs import dash_order
from inventory.dashs import dash_delivery_vs_customer
from inventory.dashs import otif
from inventory.dashs import otif_vs_supplier
from inventory.dashs import otif_test
from inventory.dashs import dash_otif_vs_sp
from inventory.dashs import dash_order_vs_supplier
from inventory.dashs import dash_delivery_vs_supplier
from inventory.dashs import dash_profil
from . import views

app_name = 'inventory'
urlpatterns = [

    path('', views.DashboardIndexView.as_view(),
         name='stock'),
    path('order_customer', views.OrderCustomerIndexView.as_view(),
        name='order_customer'),
    path('order_supplier', views.OrderSupplierIndexView.as_view(),
         name='order_supplier'),
    path('delivery_customer', views.DeliveryCustomerIndexView.as_view(),
        name='delivery_customer'),
    path('delivery_supplier', views.DeliverySupplierIndexView.as_view(),
         name='delivery_supplier'),
    path('otif', views. OtifIndexView.as_view(),
         name='otif_customer'),
    path('otif_supplier', views.OtifSupplierIndexView.as_view(),
         name='otif_supplier'),
    path('profil', views.ProfilIndexView.as_view(),
         name='profil'),
    path('index', views.IndexView.as_view(),
         name='index'),
]

stock/urls.py
from django.urls import path
from stock.dashboards import stock_value
from stock.dashboards import stock_dio
from stock.dashboards import stock_pareto
from stock.dashboards import warehouse_location
from . import views

app_name = 'stock'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:category_id>/refill/', views.refill, name='refill'),

    # # URL used in view.backup200227
    # path('product/', views.ProductListView.as_view(), name='product_list'),
    # path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    # path('product/new/', views.ProductCreate.as_view(), name='product_create'),
    # path('product/<int:pk>/edit/', views.ProductUpdate.as_view(), name='product_update'),
    # path('product/<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),
    # path('upload-csv/', views.CsvDataUpload, name="csv_data_upload"),
    # path('product/chart/', views.chart, name='product_chart'),

    path('product_index/', views.ProductIndexView.as_view(),
         name='product_index'),
    path('index/', views.StockIndexView.as_view(),
         name='stock_index'),
    path('value/', views.StockValueView.as_view(),
         name='stock_value'),
    path('dio/', views.StockDioView.as_view(),
         name='stock_dio'),
    path('pareto/', views.StockParetoView.as_view(),
         name='stock_pareto'),
    path('sale/index/', views.DeliveryIndexView.as_view(),
         name='sale_index'),
    path('purchase/index/', views.PurchaseIndexView.as_view(),
         name='purchase_index'),
    path('', views.DashboardIndexView.as_view(),
         name='index'),

]

templates/partials/_footer.html
{% load i18n %}
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>{% trans 'Copyright &copy; ORCHEST Supply Chain Analytics ' %} {% now 'Y' %}</span>
        </div>
    </div>
</footer>

templates/partials/_messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
    </div>
{% endfor %}

templates/partials/_sidebar.html
{% load static %}
{% load i18n %}

<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon">
            <img class="sidebar-brand-icon" src="{% static 'common/base/img/logo.png' %}" style="width: 100%">

            {% comment %} <i class="fas fa-signature"></i> {% endcomment %}
        </div>
            {% comment %} <img class="sidebar-brand-icon" src="{% static 'common/base/img/logo_tagline.png' %}" style="width: 55%"> {% endcomment %}
        {% comment %} <div class="sidebar-brand-text mx-3"> <sup>Supply CHain </sup>Pulse</div> {% endcomment %}
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-2">

    <!-- Nav Items -->
    {% if request.user.is_staff %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">
                <i class="fas fa-fw fa-tools"></i>
                <span>{% trans 'Admin' %}</span></a>
        </li> 
        <hr class="sidebar-divider my-2">
    {% endif %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'stock:index' %}">
            <i class="fas fa-fw fa-project-diagram"></i>
            <span>{% trans 'Dashboard' %}</span></a>
    </li> 
    {% comment %} 
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
            aria-controls="collapsePages">
            <i class="fas fa-fw fa-cubes"></i>
            <span>Stock</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'stock:stock_index' %}">
                    <span>Overview</span></a>
                </a>
                <a class="collapse-item" href="{% url 'stock:stock_value' %}">
                    <span>Stock Value</span></a>
                </a>
                <a class="collapse-item" href="{% url 'stock:stock_dio' %}">
                    <span>Stock DIO</span></a>
                </a>
                <a class="collapse-item" href="{% url 'stock:stock_pareto' %}">
                    <span>Pareto Distribution</span></a>
                </a>
            </div>
        </div>
    </li>
    {% endcomment %}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#forecasting-pages" aria-expanded="true"
            aria-controls="forecasting-pages">
            <i class="fas fa-fw fa-chart-line"></i>
            <span>{% trans 'Demand planning' %}</span>
            {% comment %} <small class="badge badge-danger">New</small> {% endcomment %}
        </a>
        <div id="forecasting-pages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                {% comment %} <a class="collapse-item" href="{% url 'forecasting:index' %}">
                    <span>{% trans 'Overview' %}</span></a>
                </a> {% endcomment %}
                {% comment %} <a class="collapse-item" href="{% url 'forecasting:version_list' %}">
                    <span>{% trans 'Input Interface' %}</span></a>
                </a> {% endcomment %}
                <a class="collapse-item" href="{% url 'forecasting:forecast_accuracy' %}">
                    <span>{% trans 'Forecast Accuracy' %}</span></a>
                </a>
                <a class="collapse-item" href="{% url 'forecasting:version_detail' %}">
                    <span>{% trans 'F-Orchest' %}</span></a>
                </a>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'deployment:deployment_dashboard' %}">
            <i class="fas fa-fw fa-truck-loading"></i>
            <span>{% trans 'Deployment' %}</span></a>
    </li> 
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-stethoscope"></i>
            <span>{% trans 'Diagnostic' %}</span>
        </a>
        <div id="collapsePages" class="collapse hide" aria-labelledby="headingPages" data-parent="#accordionSidebar" style="">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item"  href="{% url 'inventory:index' %}">
                    <span>{% trans 'Overview' %}</span></a>
                </a>
                <a class="collapse-item"  href="{% url 'inventory:profil' %}">
                    <span>{% trans 'Warehouse Profiling' %}</span></a>
                </a>
                <a class="collapse-item"  href="{% url 'inventory:stock' %}">
                    <span>{% trans 'Stock' %}</span></a>
                </a>
                <hr class="sidebar-divider black">
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">{% trans 'Customers' %}</h6>
                <a class="collapse-item" href="{% url 'inventory:order_customer' %}">{% trans 'Orders' %}</a>
                <a class="collapse-item" href="{% url 'inventory:delivery_customer' %}">{% trans 'Deliveries' %}</a>
                <a class="collapse-item" href="{% url 'inventory:otif_customer' %}">{% trans 'OTIF' %}</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">{% trans 'Suppliers' %}</h6>
                <a class="collapse-item" href="{% url 'inventory:order_supplier' %}">{% trans 'Orders' %}</a>
                <a class="collapse-item" href="{% url 'inventory:delivery_supplier' %}">{% trans 'Deliveries' %}</a>
                <a class="collapse-item" href="{% url 'inventory:otif_supplier' %}">{% trans 'OTIF' %}</a>
            </div>
        </div>
    </li>

    {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'deployment:deployment_index' %}">
            <i class="fas fa-bezier-curve"></i>
            <span>Deployment</span></a>
    </li> {% endcomment %}
    {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'stock:purchase_index' %}">
            <i class="fas fa-store"></i>
            <span>Purchase</span></a>
    </li> 
    <li class="nav-item">
        <a class="nav-link" href="{% url 'stock:sale_index' %}">
            <i class="fas fa-search-dollar"></i>
            <span>Sales</span></a>
    </li>  {% endcomment %}
    {% comment %} <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-compress-arrows-alt"></i>
            <span>(INs)</span></a>
    </li> 
     <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-external-link-alt"></i>
            <span>(OUTs)</span></a>
    </li>  {% endcomment %}

    <!-- Heading -->
    {% comment %} <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
            aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li> {% endcomment %}


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

templates/partials/_topbar.html
{% load static %}
{% load i18n %}
{% load notifications_tags %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    {% comment %} <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> {% endcomment %}

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        {% comment %} <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li> {% endcomment %}

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">{% live_notify_badge %}</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    {% trans 'Notifications center' %}
                </h6>
                <span class="notify-dropdown-menu"></span>

                <a class="dropdown-item text-center small text-gray-500" href="#">{% trans 'Show all notifications' %}</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        {% comment %} <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been
                            having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how
                            would you like them
                            sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with
                            the progress so
                            far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                            told me that people
                            say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li> {% endcomment %}




        <div class="topbar-divider d-none d-sm-block"></div>
        

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                    {% if user.is_authenticated %}
                        {{ user.get_username }}
                    {% endif %}
                </span>
                <img class="img-profile rounded-circle" src="{% static 'common/base/img/profile_pic.png' %}">
            </a>
                
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    {% trans 'Profile' %}
                </a>
                <a class="dropdown-item" href="{% url 'password_change' %}">
                    <i class="fas fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
                    {% trans 'Password change' %}
                </a>
                <!-- <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a> -->
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    {% trans 'Logout' %}
                </a>
            </div>
        </li>
    </ul>
</nav>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{% trans 'Logout' %}</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">{% trans 'Select "Logout" below if you are ready to end your current session.' %}</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">{% trans 'Cancel' %}</button>
                <a class="btn btn-primary" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
            </div>
        </div>
    </div>
</div>